config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, controllers: { registrations: "user_registrations" }
  resources :users
  resources :products do
    resources :comments
  end

  get 'static_pages/about', :as => 'about_page'

  get 'static_pages/contact', :as => 'contact_page'

  get 'static_pages/index', :as => 'home_page'

  get '/products', to: 'products#index' , :as => 'products_page'

  post 'static_pages/thank_you'

  post 'payments/create'

  root 'static_pages#landing_page'

  mount ActionCable.server => '/cable'

  resources :orders, only: [:index, :show, :create, :destroy]
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bikes of Berlin</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300|Shadows+Into+Light" rel="stylesheet">
  
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <%= csrf_meta_tags %>

  </head>

  <body>
    <nav class="navbar">
      <ul>
        <li class="Homepage"><%= link_to "Bike Berlin", home_page_path %></li>
        <li><%= link_to "About", about_page_path %></li>
        <li><%= link_to "Products", 
        products_page_path %></li>
        <li class="Contact"><%= link_to "Contact", contact_page_path %></li>
        <li class="searchbar">
          <%= form_tag("/products", method: "get") do %>
          <%= label_tag(:q, "Search for:") %>
          <%= text_field_tag(:q) %>
          <%= submit_tag("Search") %>
          <% end %>
        </li>
      </ul>
      <ul class= "nav pull-right">
        <li>
        <% if user_signed_in? %>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
        <% else %>
          <%= link_to('Login', new_user_session_path) %> 
        <% end %>
        </li>
      </ul>
    </nav>

    <% if notice %>
      <p id="notice" class="alert alert-info"><%= notice %></p>
    <% end %>

    <% if alert %>
      <p id="alert" class="alert alert-info"><%= alert %></p>
    <% end %>

    <%= yield %>

    <footer>
      &copy; 2017 Bike Berlin
    </footer>

  </body>
</html>